version: "3.8"

services:
  next-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trafic-legal-app
    restart: always
    # Portni 4000 qilib belgiladik, Nginx orqali shu portga murojaat qilasiz
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - euphoria_network

networks:
  # Bu tarmoq loyihalarni bir-biri bilan va Nginx bilan xavfsiz bog'laydi
  euphoria_network:
    external: true